### PR TITLE
Remove suggest label on vaccine page rename refferal

### PR DESCRIPTION
**Pull request by sherrif10**
https://sd-vxnaid.atlassian.net/browse/VRVU-189  cc @jdolkowski

### CODE REVIEW

**Comment by jdolkowski** [comment]
Was this change discussed with anyone? Btw please just remove the lines instead of commenting them out if the change is confirmed.

**Comment by sherrif10** [comment]
> Was this change discussed with anyone? Btw please just remove the lines instead of commenting them out if the change is confirmed.

This change was requested in the recent discussions we had from guy from UNEPI but Eva and francis can also comfirm this.

**Review by jdolkowski — APPROVED** [review]

**Comment by jdolkowski** [comment]
Please merge it after you remove the comments.

**Review by sherrif10 — COMMENTED** [review]
LGTM

**Pull request merged**
