### PR TITLE
Ensure The system takes you back to child Matching page after updatin…

### PR DESCRIPTION
**Pull request by sherrif10**
…g child
PR  https://sd-vxnaid.atlassian.net/browse/VRVU-237
 CC @jdolkowski  @druchniewicz

### CODE REVIEW

**Comment by jdolkowski** [comment]
hmmmm we should check what behaviour is desired on Wednesday

**Comment by jdolkowski** [comment]
for me personally it is not an issue

**Comment by sherrif10** [comment]
Hello @jdolkowski  , this ticket is needed, i dont know your suggestions about it.

**Comment by jdolkowski** [comment]
okay, after confirmation that it is a desired behavior, i check it and looks okay

**Pull request merged**
